In [1]:
import pandas as pd
import glob
import os
from IPython.core.display import display, HTML

In [2]:
input_file = r'/Users/shine/Documents/Project//Broomies//Watson/watson_travel'
output_file = r'/Users/kimdokyoung/Documents/dss/BOOK/Broomies/DATA/Watson/watson_travel/travel_final.csv'

In [3]:
allFile_list =[]
for i in range(100):
    allFile_list.append(glob.glob(os.path.join(input_file, 'travel_example{}.csv'.format(i))))

In [4]:
allFile_list = sum(allFile_list, [])

In [5]:
allData = []
for file in allFile_list:
    print(file)
    df = pd.read_csv(file, header=None)
    allData.append(df)

In [6]:
allData

[]

In [84]:
dataCombine = pd.concat(allData, axis=0, ignore_index=False)

In [85]:
dataCombine

,0,1,2,3,4,5,6,7,8,9,...,221,222,223,224,225,226,227,228,229,230
0,0.832173,0.675622,0.995031,0.00956916,0.944030,0.192706,0.935989,0.998418,0.995102,0.786297,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
0,0.958126,0.94261,0.989687,0.0139106,0.907168,0.803597,0.972000,0.987161,0.995441,0.794597,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
0,0.789995,0.360168,0.991991,0.000888385,0.916073,0.112968,0.983185,0.913355,0.896711,0.845146,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
0,0.972755,0.818006,0.995705,0.00958485,0.945180,0.704702,0.942283,0.991058,0.995432,0.884475,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5
0,0.854292,0.638409,0.99846,0.0018579,0.917135,0.192883,0.989676,0.990932,0.968857,0.687075,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.975661,0.639049,0.979473,0.149837,0.979545,0.426097,0.994101,0.911222,0.852919,0.721131,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.5,1.0
0,0.716525,0.626384,0.98639,0.00776363,0.882828,0.357023,0.995204,0.986937,0.951835,0.541496,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
0,0.547038,0.320613,0.968947,0.0110783,0.922317,0.659716,0.753730,0.941091,0.937025,0.732619,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
0,0.809028,0.654386,0.963179,0.00789848,0.902295,0.844786,0.991414,0.991648,0.979638,0.798020,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0
0,0.335365,0.239594,0.925994,0.0121113,0.921204,0.282767,0.995873,0.981164,0.914043,0.709690,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0

In [86]:
temp = pd.read_csv('../DATA/TRAVEL/travel_labeling_345-462.csv', index_col=0)
temp = temp[:100]

In [87]:
temp

,code,country,city_name,score,selling_count,reviews_count,guide_type,title,intro,review,travel_purpose,purpose,age_group,drop,area,company,interest,comment
0,20018,United States of America,San Francisco,4.94,1578,655,가이드 투어,요세미티 국립공원 일일투어 (글래시어포인트포함),"✔ 스냅사진, 아침간식과 점심(컵라면), 기념품샾방문, 가이드팁까지 모두포함 (팁은...",1박2일투어가 대부분이라 당일 투어도 괜찮을까 생각했는데 투어를 하고보니 전혀 걱정...,"{'purpose': 'friends', 'age_group': '20'}",friends,20,N,자연,친구,Ad,NaN
1,15749,United States of America,Las Vegas,4.91,1473,576,가이드 투어,[A코스 여행이야기]오토캠핑캬라반 1박2일(그랜드캐년.앤탈롭캐년.홀슈밴드+파웰호수),☆ 혼자 예약하셔도 OK ☆ ☆ 2인부터 출발 가능합니다 ☆ Ƹ̵̡Ӝ̵̨̄Ʒ 여...,"가이드분께서 배경 지식도 많아서 역사적인 부분을 설명해주시기도 하고, 시국이 이래서...","{'purpose': 'friends', 'age_group': '20'}",friends,20,N,자연,친구,Ad,NaN
2,7063,Canada,Toronto,4.98,268,124,가이드 투어,캐나다 자연 즐기기2- 나이아가라 폭포,나이아가라 주변을 하루 안에 두루두루 관광하려면 현지를 잘 아는 사람과 함께 기동성...,가족 4명이 갔는데 차량이 여유 있었어요 아이스와인을 소개해 주셨는데 갔다온 지 꽤...,"{'purpose': 'partner', 'age_group': '30'}",partner,30,N,자연,허니문,Ad,NaN
3,60509,Canada,Toronto,4.92,231,92,가이드 투어,[투어] 토론토에서 출발하는 나이아가라 폭포 당일치기 여행 / 영진가이드 (캐나다/...,"캐나다 하면 떠오르는 그곳, 죽기 전에 꼭 한번 봐야하는 절경! 절대 놓치면 안 ...",남편과 토론토 여행하며 영진투어를 신청하게 되었는데요~~!! 정말 가이드님 적극 추...,"{'purpose': 'honeymoon', 'age_group': '20'}",honeymoon,20,N,자연,허니문,Sh,NaN
4,31845,Canada,Toronto,4.81,138,62,가이드 투어,캐나다 투어1 - 나이아가라 폭포 일일관광 ( 단독투어 ),이 상품은 단독 상품 입니다. 개인 투어의 자유함을 느껴보세요^^* NPC(Niag...,친절하게 잘 대해주시고 단독투어라 좀더 편하게 다녀올수있었습니다. 충분한 자유시간을...,"{'purpose': 'honeymoon', 'age_group': '30'}",honeymoon,30,N,자연,가족,Ex,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,27625,Egypt,hurghada.,4.57,15,7,액티비티,후르가다: 근교 홍해의 돌고래 스노클링 투어,"본 투어는 영어로 진행되며, 다국적 여행자들과 함께하는 단체 투어로 진행됩니다. ...","2월의 홍해, 너무 좋았습니다. 배에서 이동시간과 대기시간이 길어요. 단 그 시간동...","{'purpose': 'partner', 'age_group': '30'}",partner,30,N,자연,허니문,Ad,NaN
96,46058,Egypt,Cairo,4.50,27,4,티켓/교통패스,카이로: 나일강 4시간 디너 크루즈,"본 투어는 영어로 진행되며, 다국적 여행자들과 함께하는 단체 투어로 진행됩니다. ...",호텔 앞까지 데리러 오고 데려다주고 해서 굉장히 편리했습니다 그리고 여러명을 함께 ...,"{'purpose': 'partner', 'age_group': '30'}",partner,30,N,도시,허니문,Sh,NaN
97,36473,Egypt,Cairo,4.50,17,4,가이드 투어,카이로: 기자 피라미드&스핑크스 반일 프라이빗 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔...",그냥 저냥 보통이었네요비수기라 그런지 여유롭고 한가한 여행을 하게되었습니다.. 덕분...,"{'purpose': 'friends', 'age_group': '20'}",friends,20,N,도시,친구,Kn,NaN
98,36474,Egypt,Cairo,4.00,6,3,가이드 투어,[세계 7대 불가사의] 카이로 기자 피라미드/이집트 박물관/바자르 종일 가이드 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔야...",쇼핑 다수. 털어먹을려는게 보입니다. 교통편의 좋고 사진열심히 찍어줌.픽업 시간을 ...,"{'purpose': 'children', 'age_group': '40'}",children,40,N,도시,가족,Kn,NaN
99,35729,Egypt,Cairo,3.67,10,3,가이드 투어,[카이로→알렉산드리아] 알짜배기 이집트 역사 가이드 투어,"본 투어는 영어로 진행됩니다. 여행 확인증이 아닌, 영어로 된 바우처를 지참하셔야...",관광지 입장료와 점심식사비용이 포함되어있다고 해서 예약을 했는데 막상 현지에서 가이...,"{'purpose': 'friends', 'age_group': '30'}",friends,30,N,도시,친구,Kn,NaN

In [88]:
list(temp['title'])

['요세미티 국립공원 일일투어 (글래시어포인트포함)',
 '[A코스 여행이야기]오토캠핑캬라반 1박2일(그랜드캐년.앤탈롭캐년.홀슈밴드+파웰호수)',
 '캐나다 자연 즐기기2- 나이아가라 폭포',
 '[투어] 토론토에서 출발하는 나이아가라 폭포 당일치기 여행 / 영진가이드 (캐나다/토론토)',
 ' 캐나다 투어1 - 나이아가라 폭포 일일관광 ( 단독투어 )',
 '빅토리아 (캐나다 밴쿠버) 투어 마이리얼트립 에릭과 함께하세요.',
 '[투어] (1일 투어) 살면서 꼭 가야 하는 밴프 로키여행 (1월~12월) : 캐나다/밴프',
 '휘슬러 (밴쿠버) 투어 마이리얼트립 에릭과 함께하세요.',
 '푼타카나: 패러세일링, 스노클링 크루즈, 상어와 가오리 만나기',
 '당일투어 칸쿤 필수코스! 핑크라군+익킬세노떼+치첸잇사',
 "세계 7대 불가사의 '치첸잇사' 한국인가이드 투어(매주 수/금)-멕시코 칸쿤",
 '"열정의 나라, 멕시코" 가이드 투어! (프라이빗 맞춤형 투어)',
 '태양과 떼낄라의 멕시코 - 멕시코의 매력에 빠져봅시다!',
 '나소 : 음식 & 문화 투어',
 '3시간 동안 시내 곳곳을 돌아보는 라파스 가이드 워킹 투어',
 '남미 리오 데 자네이로 투어 !!! (당일 풀옵션 )',
 '리우데자네이루: 브라질 예수상, 셀라론 계단 & 슈거로프산 선셋 투어',
 '상파울루에서 먹고 마시는 힐링여행!',
 '리우데자네이루 브라질 예수상, 슈거로프산 및 셀라론 계단 전일 투어',
 '[투어] 리오 데 자네이로 (페트로 폴리스-full day)-단독투어 (브라질/리오 데 자네이루)',
 '리우데자네이루 : 그리스도상, 슈거로프산 종일 투어 ',
 '[투어] 상파울로 차량 시티투어 :: 브라질/상파울루',
 '[투어] 리우데자네이루 한인 시티투어 (텔레그라포 포함) :: 브라질/리우데자네이루',
 '부에노스아이레스 FullDay시티투어',
 '[투어] 편안하고 안전한 시티 차량 투어(한인가이드) :: 아르헨티나/부에노스 아이레스',
 '부에노스 아이레스 반일 투어',
 '부에노스아이레스: 가이드와 함께하는 종일 도보 투어',
 '남미의 파리! 부에노스 아이레스 스토리텔링 투어!',
 '부에노스아이레스 산타 수산나 가우초  FullDay 투어',
 '[단 1명도 출발!소규모 투어] 산티아고 워킹 시티 투어 3시간',
 '산호세 출발 : 거북이의 땅 또르뚜게로 국립 공원 투어',
 '산호세에서 떠나는 이라수(Irazu) 화산, 오로시(Orosi) 계곡, 랑카스터(Lankaster) 정원 투어',
 '산호세에서 떠나는 코스타리카 종일 투어',
 '보고타: 자전거를 타고 둘러보는 가이드 시티 투어',
 '[투어] 올드카 낭만투어 & 올드아바나 워킹투어 (한국어) :: 쿠바/아바나',
 '[투어] 올드 아바나 워킹투어 (한국어) :: 쿠바/아바나',
 '[투어] 아바나 필수! 현지 선생님과 즐기는 살사수업 :: 쿠바/아바나',
 '[투어] 올드카(Old Car) 낭만투어 (한국어) :: 쿠바/아바나',
 '[리마] 반나절 소그룹 시티 투어',
 '리마에서 출발하는 파차카막/바랑코 반일 투어',
 '[한국인투어] 호빗 마을과 반짝반짝 와이토모 반딧불동굴(단독투어) :: 뉴질랜드/오클랜드',
 '오클랜드 : 호비튼 마을 & 와이토모 동굴 투어',
 '퀸스타운 : 밀포드 사운드 투어 (크루즈 포함 / 7시 출발)',
 '[한국인투어] 반지의제왕, 호빗을 봤다면 호빗튼으로!!(단독투어) :: 뉴질랜드/오클랜드',
 '[한국인투어] 반짝반짝 와이토모 반딧불 동굴 투어 (단독투어) :: 뉴질랜드/오클랜드',
 '[투어] 오클랜드 : 코로만델 명소 단독투어 (뉴질랜드/오클랜드)',
 '오클랜드 단독자유여행',
 '[투어] 특가! 포트스테판+와이너리&씨푸드뷔페+워킹투어&포포크림+비자무료! (호주/시드니)',
 '[투어]힘내라 한국/알차고편안한 소그룹여행/그레이트오션로드,12사도,런던브릿지:호주/멜버른',
 '[투어] 블루마운틴+킹스테이블+페더데일+무료워킹투어 Bonus 선물이벤트 :: 호주/시드니',
 '[투어] 특가! 블루마운틴&페더데일+킹스테이블랜드+워킹투어&포포크림+비자무료(호주/시드니)',
 '[투어][가을이벤트](매일)[+3월벤츠소그룹]절대가격/그레이트오션[런던브릿지]:호주/멜버른',
 '[투어] 3 in 1/소확행특가/그레이트오션로드,퍼핑빌리기관차,펭귄퍼레이드::호주/멜버른',
 '[투어] [뭉쳐야싸다 콤보] 포트스테판&블루마운틴+무료워킹투어,포포크림:: 호주/시드니',
 '[리얼가이드선정 감사세일/선착순한정] 그레이트오션로드로 가는 감동투어 ::호주/멜버른',
 '[괌] 만족도 1위! 괌 오션벤처 돌핀 크루즈와 함께 맑고 깨끗한 바다에서 힐링하기!',
 '[괌] 김태광가이드와 함께하는  남부투어, 괌 로컬 분위기를 가장 잘 느낄 수 있는 투어',
 '괌 씨워커',
 '괌 돌핀크루즈+피쉬아이 해중전망대',
 '반나절만에 즐기는 괌 시내투어(사랑의 절벽포함)',
 '[투어] 후기만족1위! 괌돌핀크루즈+면세점할인쿠폰+소아스노쿨보드+참치회음료+스노쿨링낚시',
 '[투어] 괌 세일즈바베큐 1+1 프로모션 소아100원!무제한맥주샐러드&1만원면세점할인쿠폰',
 '[투어] 좋은후기가장많은 고퀄 별빛투어 with 한국인 가이드 Joe :: 사이판',
 '[투어] [후기만족1위]사이판 그로토 ( 그루토 ) 한인업체+스노클링&다이빙체험+북부관광',
 '[투어] 좋은후기많은 사이판 마나가하 +해양스포츠  (아이스박스&돗자리 무료제공) ',
 '[사이판] 마나가하섬 1일팩 (파라세일링+마나가하섬+보트)+아이스박스와 돗자리 포함',
 '[투어] 그로토 스노쿨링 (수중사진무료제공) &체험다이빙  :: 사이판',
 '[투어] 제리아저씨의 공연과 함께하는 사이판 선셋 BBQ디너 크루즈 ',
 '[사이판] 사이판 별빛 투어 (야간 투어)',
 '[투어] B 퍼펙트 락 아일랜드 스노쿨링 (Perfect Rock Island):: 팔라우',
 '[투어] C 낭만 별빛 낚시 (퍼밋포함) (Night Fishing Tour) :: 팔라우',
 'D 팔라우 레전드 스파 마사지 (Legend Spa & Massage)',
 '[투어] A 스페셜 락 아일랜드 스노클링 (Special Rock Island)',
 '[투어] 펀 다이빙 (팔라우/락아일랜드)',
 '[투어] 스페셜 락 아일랜드 투어 (팔라우/락아일랜드)',
 '[투어] 나이트 카약 투어 (팔라우/락아일랜드)',
 '[투어] 롱비치&밀키웨이 투어 (팔라우/락아일랜드)',
 '케이프타운 희망봉 1일 투어',
 "케이프타운 베스트 1일투어 (일명 '일찍 일어나는 새' 투어)",
 '[투어] 크루거내셔날파크 사파리 2박 3일 투어 (남아프리카공화국/요하네스버그) ',
 '[투어] 남아공  핵심 시내투어(남아프리카공화국/요하네스버그)',
 '케이프타운 : 케이프 와인랜드 와인 체험 투어',
 '마라케시에서 출발하는 자고라 사하라 사막 여행 (2일)',
 '마라케시에서 메르조가까지 사막사파리 3일 투어 ',
 '마라케시 출발: 사하라사막 메르주가 에르그셰비 3일 투어',
 '마라케시 출발: 와르자자트와 아이트 벤하두 종일 투어',
 '마라케시에서 출발하는 에사우이라 종일 투어',
 '마라케시 출발 : 2박 3일 사하라 사막 투어',
 '마라케시 사막 & 야자 숲 사륜 오토바이 투어',
 '마라케시의 역사를 돌아보는 4시간 투어',
 '마라케시 출발: 오조드 폭포로 떠나는 종일 투어',
 '모리셔스: 르몽산(UNESCO 자연 유산) 친환경 하이킹',
 '모리셔스: 블랙리버 해안에서 돌고래와 수영하고 고래를 볼 수 있는 스피드보트 투어',
 '모리셔스: 자연 그대로를 즐기는 남서부 종일 단체 투어',
 '모리셔스 : 블랙 리버 수영 & 돌고래 스피드 보트 투어',
 '후르가다:  근교 홍해의 돌고래 스노클링 투어',
 '카이로: 나일강 4시간 디너 크루즈',
 '카이로: 기자 피라미드&스핑크스 반일 프라이빗 투어',
 '[세계 7대 불가사의] 카이로 기자 피라미드/이집트 박물관/바자르 종일 가이드 투어',
 '[카이로→알렉산드리아] 알짜배기 이집트 역사 가이드 투어']

In [89]:
dataCombine['title'] = np.nan
dataCombine['title'] = list(temp['title'])
dataCombine

,0,1,2,3,4,5,6,7,8,9,...,222,223,224,225,226,227,228,229,230,title
0,0.832173,0.675622,0.995031,0.00956916,0.944030,0.192706,0.935989,0.998418,0.995102,0.786297,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,요세미티 국립공원 일일투어 (글래시어포인트포함)
0,0.958126,0.94261,0.989687,0.0139106,0.907168,0.803597,0.972000,0.987161,0.995441,0.794597,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,[A코스 여행이야기]오토캠핑캬라반 1박2일(그랜드캐년.앤탈롭캐년.홀슈밴드+파웰호수)
0,0.789995,0.360168,0.991991,0.000888385,0.916073,0.112968,0.983185,0.913355,0.896711,0.845146,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,캐나다 자연 즐기기2- 나이아가라 폭포
0,0.972755,0.818006,0.995705,0.00958485,0.945180,0.704702,0.942283,0.991058,0.995432,0.884475,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5,[투어] 토론토에서 출발하는 나이아가라 폭포 당일치기 여행 / 영진가이드 (캐나다/...
0,0.854292,0.638409,0.99846,0.0018579,0.917135,0.192883,0.989676,0.990932,0.968857,0.687075,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,캐나다 투어1 - 나이아가라 폭포 일일관광 ( 단독투어 )
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.975661,0.639049,0.979473,0.149837,0.979545,0.426097,0.994101,0.911222,0.852919,0.721131,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.5,1.0,후르가다: 근교 홍해의 돌고래 스노클링 투어
0,0.716525,0.626384,0.98639,0.00776363,0.882828,0.357023,0.995204,0.986937,0.951835,0.541496,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,카이로: 나일강 4시간 디너 크루즈
0,0.547038,0.320613,0.968947,0.0110783,0.922317,0.659716,0.753730,0.941091,0.937025,0.732619,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,카이로: 기자 피라미드&스핑크스 반일 프라이빗 투어
0,0.809028,0.654386,0.963179,0.00789848,0.902295,0.844786,0.991414,0.991648,0.979638,0.798020,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,[세계 7대 불가사의] 카이로 기자 피라미드/이집트 박물관/바자르 종일 가이드 투어
0,0.335365,0.239594,0.925994,0.0121113,0.921204,0.282767,0.995873,0.981164,0.914043,0.709690,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,[카이로→알렉산드리아] 알짜배기 이집트 역사 가이드 투어

In [94]:
dataCombine.to_csv(output_file, index=False)

In [95]:
result = pd.read_csv('../DATA/Watson/watson_travel/travel_final.csv')

In [96]:
result

,0,1,2,3,4,5,6,7,8,9,...,222,223,224,225,226,227,228,229,230,title
0,0.8321733149789752,0.6756223611437921,0.9950311402999588,0.009569162457184976,0.944030,0.192706,0.935989,0.998418,0.995102,0.786297,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,요세미티 국립공원 일일투어 (글래시어포인트포함)
1,0.9581263660882982,0.9426103124830224,0.989686850141032,0.013910569916287864,0.907168,0.803597,0.972000,0.987161,0.995441,0.794597,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,[A코스 여행이야기]오토캠핑캬라반 1박2일(그랜드캐년.앤탈롭캐년.홀슈밴드+파웰호수)
2,0.789994532812386,0.36016849991823763,0.9919907034679548,0.0008883851258243426,0.916073,0.112968,0.983185,0.913355,0.896711,0.845146,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,캐나다 자연 즐기기2- 나이아가라 폭포
3,0.972754574510745,0.8180063054900558,0.9957053654650224,0.00958484830830558,0.945180,0.704702,0.942283,0.991058,0.995432,0.884475,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,0.5,[투어] 토론토에서 출발하는 나이아가라 폭포 당일치기 여행 / 영진가이드 (캐나다/...
4,0.8542921170532978,0.6384088236992435,0.9984601165511824,0.0018578960104999047,0.917135,0.192883,0.989676,0.990932,0.968857,0.687075,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,캐나다 투어1 - 나이아가라 폭포 일일관광 ( 단독투어 )
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.9756608933681562,0.6390490885500151,0.9794733652837968,0.14983651158622135,0.979545,0.426097,0.994101,0.911222,0.852919,0.721131,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.5,1.0,후르가다: 근교 홍해의 돌고래 스노클링 투어
96,0.7165248963811786,0.6263836405106966,0.9863903574887573,0.007763628169458693,0.882828,0.357023,0.995204,0.986937,0.951835,0.541496,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,카이로: 나일강 4시간 디너 크루즈
97,0.5470381512826418,0.3206129774256984,0.9689474503361988,0.011078285912966336,0.922317,0.659716,0.753730,0.941091,0.937025,0.732619,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,카이로: 기자 피라미드&스핑크스 반일 프라이빗 투어
98,0.8090275577849287,0.6543860880791825,0.9631792024062792,0.0078984841706744,0.902295,0.844786,0.991414,0.991648,0.979638,0.798020,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,[세계 7대 불가사의] 카이로 기자 피라미드/이집트 박물관/바자르 종일 가이드 투어
99,0.3353651821478064,0.2395935224191849,0.9259935136775692,0.012111341013126777,0.921204,0.282767,0.995873,0.981164,0.914043,0.709690,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.5,1.0,[카이로→알렉산드리아] 알짜배기 이집트 역사 가이드 투어